inputs:
    script:
        description: 'Script to be passed to the docker image'
        required: true

    emscripten_cache_dir:
        description: 'Emscripten cache directory'
        default: /github/workspace/.emscripten_cache
    yarn_cache_dir:
        description: 'Yarn cache directory'
        default: /github/workspace/.yarn_cache
    ccache_dir:
        description: 'Ccache directory'
        default: /github/workspace/.ccache

runs:
    using: 'docker'
    image: 'ankoh/dashql-ci-action:master'
    env:
        EM_CACHE: ${{ inputs.emscripten_cache_dir }}
        YARN_CACHE_FOLDER: ${{ inputs.yarn_cache_dir }}
        CCACHE_DIR: ${{ inputs.ccache_dir }}
        CCACHE_BASEDIR: /github/workspace/
    args:
        - bash -c "${{ inputs.script }}"
